version: '2'
services:
  db:
    image: postgres
    ports: 
      - "5342"
  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/nuitinfo
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - RAILS_ENV=development

